name: C# CI

on:
  schedule:
  # each fifteen day of month
  - cron: "0 0 15 * *"
  push:
    branches: [ "main" ]
    paths:
      - 'csharp/**'
      - '.github/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'csharp/**'
      - '.github/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: csharp/global.json

      - name: Restore dependencies
        run: |
          cd csharp
          dotnet restore Bingo.sln

      - name: Build Solution
        run: |
          cd csharp
          dotnet build Bingo.sln --no-restore --configuration Release

      - name: Run Tests
        run: |
          cd csharp
          dotnet test Bingo.sln --no-build --configuration Release --logger "trx;LogFileName=test_results.xml"

