name: Java CI with Maven

on:
  schedule:
  # each fifteen day of month
  - cron: "0 0 15 * *"
  push:
    paths:
      - 'java/**'
      - '.github/**'
  pull_request:
    paths:
      - 'java/**'
      - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
          cd java
          mvn -B package --file pom.xml
