name: Ruby CI with Minitest

on:
  schedule:
  # each fifteen day of month
  - cron: "0 0 15 * *"
  push:
    branches: ["main"]
    paths:
      - "ruby/**"
      - ".github/**"
  pull_request:
    branches: ["main"]
    paths:
      - "ruby/**"
      - ".github/**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"

      - name: Run tests
        run: |
          cd ruby
          ruby bingo_board_test.rb
          ruby bingo_board_bdd_test.rb
